// Code generated by "stringer -type=suit,rank"; DO NOT EDIT.

package deck

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Spade-1]
	_ = x[Heart-2]
	_ = x[Club-3]
	_ = x[Diamond-4]
}

const _suit_name = "SpadeHeartClubDiamond"

var _suit_index = [...]uint8{0, 5, 10, 14, 21}

func (i suit) String() string {
	i -= 1
	if i < 0 || i >= suit(len(_suit_index)-1) {
		return "suit(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _suit_name[_suit_index[i]:_suit_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Ace-1]
	_ = x[Two-2]
	_ = x[Three-3]
	_ = x[Four-4]
	_ = x[Five-5]
	_ = x[Six-6]
	_ = x[Seven-7]
	_ = x[Eight-8]
	_ = x[Nine-9]
	_ = x[Ten-10]
	_ = x[Jack-11]
	_ = x[Queen-12]
	_ = x[King-13]
	_ = x[Joker-14]
}

const _rank_name = "AceTwoThreeFourFiveSixSevenEightNineTenJackQueenKingJoker"

var _rank_index = [...]uint8{0, 3, 6, 11, 15, 19, 22, 27, 32, 36, 39, 43, 48, 52, 57}

func (i rank) String() string {
	i -= 1
	if i < 0 || i >= rank(len(_rank_index)-1) {
		return "rank(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _rank_name[_rank_index[i]:_rank_index[i+1]]
}
